import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import manifest from "./manifest";

const ROOT = process.cwd();

/** Reads width/height from a PNG's IHDR chunk (bytes 16–24). */
function pngSize(file) {
  const buf = readFileSync(file);
  expect(buf.subarray(1, 4).toString("ascii"), `${file} is not a PNG`).toBe("PNG");
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

describe("manifest", () => {
  const m = manifest();

  it("declares a name, scope, and start_url", () => {
    expect(m.name).toContain("Tarazu");
    expect(m.short_name).toBe("Tarazu");
    expect(m.scope).toBe("/");
    // Someone installing this wants the workspace, not the marketing page.
    expect(m.start_url).toBe("/app");
  });

  it("uses the brand background and theme colour", () => {
    expect(m.background_color).toBe("#0E0F12");
    expect(m.theme_color).toBe("#0E0F12");
  });

  it("declares a maskable icon", () => {
    expect(m.icons.some((i) => i.purpose === "maskable")).toBe(true);
  });

  // Manifest icons must use stable /public paths — the App Router file
  // convention content-hashes its URLs, which a manifest cannot reference.
  it("points every icon at a file that actually exists at the declared size", () => {
    for (const icon of m.icons) {
      const file = path.join(ROOT, "public", icon.src);
      expect(existsSync(file), `missing ${icon.src}`).toBe(true);
      const [w, h] = icon.sizes.split("x").map(Number);
      expect(pngSize(file), `${icon.src} is not ${icon.sizes}`).toEqual({ width: w, height: h });
      expect(icon.type).toBe("image/png");
    }
  });
});

// These are checked-in binaries generated by scripts/generate-icons.mjs. A binary
// cannot carry a comment, so this is where "these must exist at these sizes" lives.
describe("icon assets", () => {
  it("ships an SVG source that the raster assets derive from", () => {
    const svg = readFileSync(path.join(ROOT, "app", "icon.svg"), "utf8");
    expect(svg).toContain("<svg");
    // An opaque plate, not a transparent mark: the crossbar is bone and would
    // vanish against a light browser tab strip.
    expect(svg).toContain("#0E0F12");
  });

  it("ships a 180x180 apple touch icon", () => {
    expect(pngSize(path.join(ROOT, "app", "apple-icon.png"))).toEqual({
      width: 180,
      height: 180,
    });
  });

  it("ships a real .ico, not a renamed PNG", () => {
    const ico = readFileSync(path.join(ROOT, "app", "favicon.ico"));
    // ICO header: reserved=0, type=1 (icon), then the image count.
    expect(ico.readUInt16LE(0)).toBe(0);
    expect(ico.readUInt16LE(2)).toBe(1);
    expect(ico.readUInt16LE(4)).toBeGreaterThanOrEqual(1);
  });
});
